version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - goconst
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 400
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 170
  exclusions:
    generated: lax
    paths:
      - "testhelpers/*"
      - "examples/*"
formatters:
  enable:
    - gofmt
    - goimports