name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 17 * * *'

jobs:
  shell-ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Lint shell scripts, ignoring third-party files
      run: |
        find . -name "*.sh" | grep -v site | grep -v vendor | grep -v node_modules | grep -v demo/demo-magic > shell_files.out
        shellcheck $(cat shell_files.out)  

  go-ci:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: kptdev/porch/.github/actions/setup-go-kpt@main
      with:
        go-version-file: go/fn/go.mod
        install-kpt: 'false'
    - name: Build, Test, Lint
      run: hack/ci-validate-go.sh